name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: stable

      - name: 安装依赖
        run: flutter pub get

      - name: 编译 Release APK
        run: flutter build apk --release --no-shrink

      - name: 上传APK成品
        uses: actions/upload-artifact@v4
        with:
          name: 防风控守护_APK
          path: build/app/outputs/flutter-apk/app-release.apk
