name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 配置 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: stable
          cache: true

      - name: 检查 Flutter 环境
        run: flutter doctor -v

      - name: 安装依赖
        run: flutter pub get

      - name: 编译 APK
        run: flutter build apk --release --verbose

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: 防风控守护_APK
          path: build/app/outputs/flutter-apk/app-release.apk
